import 'package:truco/dados/carta_firebase.dart';

class Baralho {
  static List<CartaFirebase> cartas = [
    CartaFirebase(carta: '3_1', valorCarta: 9, valorNaipe: 1),
    CartaFirebase(carta: '3_2', valorCarta: 9, valorNaipe: 2),
    CartaFirebase(carta: '3_3', valorCarta: 9, valorNaipe: 3),
    CartaFirebase(carta: '3_4', valorCarta: 9, valorNaipe: 4),
    CartaFirebase(carta: '2_1', valorCarta: 8, valorNaipe: 1),
    CartaFirebase(carta: '2_2', valorCarta: 8, valorNaipe: 2),
    CartaFirebase(carta: '2_3', valorCarta: 8, valorNaipe: 3),
    CartaFirebase(carta: '2_4', valorCarta: 8, valorNaipe: 4),
    CartaFirebase(carta: 'a_1', valorCarta: 7, valorNaipe: 1),
    CartaFirebase(carta: 'a_2', valorCarta: 7, valorNaipe: 2),
    CartaFirebase(carta: 'a_3', valorCarta: 7, valorNaipe: 3),
    CartaFirebase(carta: 'a_4', valorCarta: 7, valorNaipe: 4),
    CartaFirebase(carta: 'k_1', valorCarta: 6, valorNaipe: 1),
    CartaFirebase(carta: 'k_2', valorCarta: 6, valorNaipe: 2),
    CartaFirebase(carta: 'k_3', valorCarta: 6, valorNaipe: 3),
    CartaFirebase(carta: 'k_4', valorCarta: 6, valorNaipe: 4),
    CartaFirebase(carta: 'j_1', valorCarta: 5, valorNaipe: 1),
    CartaFirebase(carta: 'j_2', valorCarta: 5, valorNaipe: 2),
    CartaFirebase(carta: 'j_3', valorCarta: 5, valorNaipe: 3),
    CartaFirebase(carta: 'j_4', valorCarta: 5, valorNaipe: 4),
    CartaFirebase(carta: 'q_1', valorCarta: 4, valorNaipe: 1),
    CartaFirebase(carta: 'q_2', valorCarta: 4, valorNaipe: 2),
    CartaFirebase(carta: 'q_3', valorCarta: 4, valorNaipe: 3),
    CartaFirebase(carta: 'q_4', valorCarta: 4, valorNaipe: 4),
    CartaFirebase(carta: '7_1', valorCarta: 3, valorNaipe: 1),
    CartaFirebase(carta: '7_2', valorCarta: 3, valorNaipe: 2),
    CartaFirebase(carta: '7_3', valorCarta: 3, valorNaipe: 3),
    CartaFirebase(carta: '7_4', valorCarta: 3, valorNaipe: 4),
    CartaFirebase(carta: '6_1', valorCarta: 2, valorNaipe: 1),
    CartaFirebase(carta: '6_2', valorCarta: 2, valorNaipe: 2),
    CartaFirebase(carta: '6_3', valorCarta: 2, valorNaipe: 3),
    CartaFirebase(carta: '6_4', valorCarta: 2, valorNaipe: 4),
    CartaFirebase(carta: '5_1', valorCarta: 1, valorNaipe: 1),
    CartaFirebase(carta: '5_2', valorCarta: 1, valorNaipe: 2),
    CartaFirebase(carta: '5_3', valorCarta: 1, valorNaipe: 3),
    CartaFirebase(carta: '5_4', valorCarta: 1, valorNaipe: 4),
    CartaFirebase(carta: '4_1', valorCarta: 0, valorNaipe: 1),
    CartaFirebase(carta: '4_2', valorCarta: 0, valorNaipe: 2),
    CartaFirebase(carta: '4_3', valorCarta: 0, valorNaipe: 3),
    CartaFirebase(carta: '4_4', valorCarta: 0, valorNaipe: 4),
  ];
}
